#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod camera_test;
mod config_ui;
mod dialogs;
mod framebuffer;
mod handle;
mod input;
mod macos_sandbox;
mod safe_stop;
mod scsi_menu;
mod serial_console;
mod settings;
mod single_instance;

use config_ui::{cfg_to_toml, show_tab, ConfigAction, JitEnv, Tab};
use dialogs::create_disk::CreateDiskDialog;
use dialogs::new_machine::{distribute_ram, NewMachineDialog};
use eframe::egui;
use egui::{Color32, RichText, ViewportCommand};
use handle::{Cmd, EmulatorHandle, Evt};
use iris::config::MachineConfig;
use safe_stop::{evaluate, reason_lines};
use settings::{GuiSettings, UI_SCALE_MAX, UI_SCALE_MIN, WINDOW_DEFAULT_SIZE};
use std::path::PathBuf;

/// Decode the bundled window/taskbar icon (256×256 RGBA PNG, generated by
/// `scripts/generate-icon.sh` from `iris-gui/assets/icon-original.png`).
/// Decoded with the `png` crate that iris-gui already depends on, so no extra
/// image dependency is pulled in.
fn load_icon() -> egui::IconData {
    const ICON_PNG: &[u8] = include_bytes!("../assets/icons/icon-256.png");
    let decoder = png::Decoder::new(std::io::Cursor::new(ICON_PNG));
    let mut reader = decoder.read_info().expect("decode icon PNG header");
    let mut rgba = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut rgba).expect("decode icon PNG pixels");
    rgba.truncate(info.buffer_size());
    egui::IconData {
        rgba,
        width: info.width,
        height: info.height,
    }
}

/// Largest aspect-preserving size (egui points) that fits `avail` for a
/// framebuffer whose native pixel dimensions are `px`.
fn fb_fit_size(avail: egui::Vec2, px: egui::Vec2) -> egui::Vec2 {
    let fb_aspect = px.x / px.y;
    if avail.x / avail.y > fb_aspect {
        egui::vec2(avail.y * fb_aspect, avail.y)
    } else {
        egui::vec2(avail.x, avail.x / fb_aspect)
    }
}

/// True when `scale` (device pixels per emulated pixel) is close enough to a
/// positive integer that nearest-neighbour sampling stays pixel-perfect. Off
/// an integer, bilinear filtering avoids uneven pixel doubling.
fn is_integer_scale(scale: f32) -> bool {
    let rounded = scale.round();
    rounded >= 1.0 && (scale - rounded).abs() <= 0.01
}

fn main() -> eframe::Result<()> {
    env_logger::init();
    // Prevent the iris lib from calling process::exit on guest soft-power-off
    // or CI `quit`. iris-gui never wants the embedder to die from a guest event.
    // Set this once, before any worker thread can read it.
    std::env::set_var("IRIS_NO_EXIT_ON_POWEROFF", "1");
    // Terminate a still-alive previous instance (a crash/hang or forgotten
    // copy that would otherwise keep the monitor/serial ports bound) and claim
    // the single-instance lock for ourselves.
    single_instance::acquire();
    let prefs = GuiSettings::load();
    // Re-acquire macOS sandbox access to previously user-selected files (disk
    // images, PROM, ISOs, …) before any machine can open them. No-op elsewhere.
    macos_sandbox::restore(&prefs.bookmarks);
    // Under the App Sandbox a compressed HD CHD's `.diff.chd` sidecar can't be
    // created next to the parent (its directory isn't writable). Redirect diffs
    // into our writable data dir (container-redirected under the sandbox). Off
    // the App Store build the diff stays beside the parent (no sandbox).
    #[cfg(feature = "appstore")]
    if let Some(d) = dirs::data_dir() {
        std::env::set_var("IRIS_CHD_DIFF_DIR", d.join("iris").join("chd-diffs"));
    }
    // Force the interpreter on the Mac App Store build. Cranelift (MIPS JIT and
    // the always-on REX3 draw-shader JIT) allocates executable memory with
    // mmap+mprotect, not MAP_JIT. The App Sandbox only permits MAP_JIT pages
    // (com.apple.security.cs.allow-jit is the sole code-signing entitlement MAS
    // allows; allow-unsigned-executable-memory / disable-executable-page-
    // protection are rejected by App Review), so the first JITed REX3 draw is
    // killed with SIGKILL/CODESIGNING "Invalid Page" on the REX3-Processor
    // thread — right after the emulator window opens, before any video. Set
    // once, before any worker thread (CPU / REX3) can read it.
    #[cfg(feature = "appstore")]
    std::env::set_var("IRIS_NO_JIT", "1");
    let viewport = egui::ViewportBuilder::default()
        .with_title("iris — SGI Indy emulator")
        // app_id sets the X11 WM_CLASS / Wayland app_id so the compositor can
        // match an installed .desktop/icon (icons regenerated by
        // scripts/generate-icon.sh from iris-gui/assets/icon-original.png).
        .with_app_id("iris-gui")
        .with_icon(load_icon())
        // Open large enough for the 1280×1024 display + chrome so it looks right
        // immediately; clamp to the monitor so it can't overflow a smaller
        // screen. Persisted size (once saved) takes precedence over the default.
        .with_inner_size(prefs.window_size.unwrap_or(WINDOW_DEFAULT_SIZE))
        .with_clamp_size_to_monitor_size(true)
        // Start hidden so the first frame can fit the window to the monitor
        // (see the reveal logic in `update`) before it's shown — the window
        // then appears already at the right size instead of opening at the
        // default and visibly resizing.
        .with_visible(false);
    // Intentionally do NOT restore fullscreen on launch — the app always opens
    // windowed; fullscreen is only ever entered when the user asks (F11).
    let opts = eframe::NativeOptions {
        viewport,
        ..Default::default()
    };
    eframe::run_native(
        "iris-gui",
        opts,
        Box::new(|cc| {
            cc.egui_ctx.set_zoom_factor(prefs.ui_scale.clamp(UI_SCALE_MIN, UI_SCALE_MAX));
            Ok(Box::new(App::new(prefs)))
        }),
    )
}

struct App {
    prefs: GuiSettings,
    cfg: MachineConfig,
    /// Path to an iris.toml that was *imported* (for re-export). None for
    /// machines that originated from the GUI.
    cfg_path: Option<PathBuf>,
    /// Marks the current cfg as having unsaved (in-memory) changes.
    cfg_dirty: bool,
    /// Timestamp of the most recent edit; used to debounce auto-save.
    cfg_dirty_since: Option<std::time::Instant>,
    jit: JitEnv,
    tab: Tab,
    emu: EmulatorHandle,
    toast: Option<(String, std::time::Instant)>,
    fullscreen: bool,
    stop_modal: Option<StopModal>,
    missing_modal: Option<MissingDiskModal>,
    /// Set when the user clicks "Use embedded PROM"; drives a confirmation modal.
    confirm_embedded_prom: bool,
    new_machine: NewMachineDialog,
    create_disk: CreateDiskDialog,
    /// If true, central panel shows the tabbed config editor; otherwise the
    /// welcome/status summary panel (default — most config lives in menus).
    show_config_editor: bool,
    save_state_name: String,
    restore_state_name: String,
    /// egui texture holding the most recent REX3 framebuffer. Allocated
    /// lazily on the first frame that needs it.
    fb_tex: Option<egui::TextureHandle>,
    /// Sequence number of the last frame we uploaded; used to skip the
    /// upload when the renderer hasn't produced a new frame.
    last_fb_seq: u64,
    /// Filter the framebuffer texture is currently uploaded with: `true` =
    /// NEAREST (crisp; used at integer device-pixel scales), `false` = LINEAR
    /// (smooths the uneven pixel doubling at fractional scales). Tracked so we
    /// only re-upload when the integer/fractional status actually flips.
    fb_nearest: bool,
    /// Current on-screen magnification of the emulated display: logical points
    /// per emulated pixel (1.0 = native, i.e. the picture at its true size; <1
    /// shrunk to fit; >1 enlarged). 0.0 until the first frame is drawn. Shown in
    /// the status footer next to MIPS. Crispness (NEAREST vs LINEAR) tracks the
    /// *device-pixel* scale via `fb_nearest`, which this can differ from on HiDPI.
    fb_scale: f32,
    /// Set on Start (and on a VM/UI scale change); consumed on the next real
    /// REX3 frame to resize the window so the display lands at the chosen VM
    /// scale (clamped + ½×-snapped to fit the monitor; see `framebuffer_panel`).
    pending_fb_snap: bool,
    /// True on a first-ever launch (no persisted window size). Consumed on the
    /// first frame that knows the monitor size, to fit the window to a 1280×1024
    /// display at the chosen VM scale so it opens at a sensible, windowed size
    /// before the first Start. Returning users just reopen at their saved size.
    pending_launcher_fit: bool,
    /// The window starts hidden (`with_visible(false)`) so the first frame can
    /// fit it to the monitor before it's shown. Set true once we've revealed it.
    revealed: bool,
    /// Frames rendered since launch; gates the reveal so the startup fit's
    /// resize is applied before the window appears (and as a hard fallback so a
    /// missing monitor size can't leave the window hidden).
    startup_frame: u32,
    /// Per-frame state for the egui→PS2 input pump (modifier diff,
    /// mouse button mask, last cursor position).
    input_state: input::InputState,
    /// Previous frame's `cpu_halted` status, so we can edge-detect the guest
    /// becoming "safe to stop" and auto-release the captured mouse/keyboard
    /// exactly once on that transition. Reset to true on Start so the initial
    /// idle-at-PROM state doesn't count as a halt.
    prev_cpu_halted: bool,
    /// Active "Test Camera" preview (None when the window is closed). Opening it
    /// starts host-camera capture; dropping it releases the device.
    camera_test: Option<camera_test::CameraTest>,
    /// egui texture for the camera-test preview + the last frame seq uploaded.
    camera_test_tex: Option<egui::TextureHandle>,
    camera_test_seq: u64,
    /// Active in-app IRIX serial-console viewer (None when closed). Connects to
    /// the loopback serial server; dropping it closes the connection.
    serial_console: Option<serial_console::SerialConsole>,
    /// Pending line typed into the serial console input field.
    serial_input: String,
    /// Whether the "How camera & networking work" Help window is open.
    show_help_info: bool,
}

struct StopModal {
    lines: Vec<String>,
}

/// One SCSI device that is missing its backing file at Start time.
struct MissingDisk {
    id: u8,
    path: String,
    cdrom: bool,
}

/// True if `path` can actually be *read*. The Start preflight uses this instead
/// of `Path::exists()` because under the macOS App Sandbox a user-selected file
/// we hold no current grant for (e.g. a disk image picked in a previous session,
/// before a security-scoped bookmark was minted — see [`macos_sandbox`]) still
/// `stat()`s as present, so `exists()` would wave it through to `Machine::new`,
/// which then fails to attach the disk. We probe an actual read (not just an
/// `open`) because the sandbox can permit `open()` yet deny `read()` once a
/// grant has lapsed — so opening alone would still slip past the check and only
/// fail deep in the CHD/image loader. Catching it here routes the disk to the
/// missing-disk modal, where the user can re-select or detach it.
fn disk_readable(path: &str) -> bool {
    use std::io::Read;
    if path.is_empty() {
        return false;
    }
    let Ok(mut f) = std::fs::File::open(path) else {
        return false;
    };
    let mut probe = [0u8; 1];
    matches!(f.read(&mut probe), Ok(n) if n >= 1)
}

/// Modal shown when one or more SCSI image files are missing on Start.
/// `Machine::new` would otherwise call `std::process::exit(1)` and take
/// the whole GUI down with it.
struct MissingDiskModal {
    missing: Vec<MissingDisk>,
}

impl App {
    fn new(mut prefs: GuiSettings) -> Self {
        // Resolution order on startup:
        //   1. prefs.active_machine present + in prefs.machines → load it.
        //   2. legacy prefs.last_config TOML still on disk → migrate it as
        //      a new named machine and adopt it.
        //   3. otherwise: open the New Machine dialog.
        let mut cfg = MachineConfig::default();
        let mut cfg_path: Option<PathBuf> = None;
        let mut opened_new_machine = false;
        let mut new_machine = NewMachineDialog::default();

        if let Some(name) = prefs.active_machine.clone() {
            if let Some(stored) = prefs.machines.get(&name).cloned() {
                cfg = stored;
            } else {
                // Stale pointer — fall through to migrate / dialog.
                prefs.active_machine = None;
            }
        }
        if prefs.active_machine.is_none() {
            if let Some(p) = prefs.last_config.clone() {
                if p.exists() {
                    cfg = MachineConfig::load_toml(&p.to_string_lossy());
                    cfg_path = Some(p.clone());
                    let stem = p.file_stem().and_then(|s| s.to_str()).unwrap_or("imported");
                    let name = prefs.unique_name(stem);
                    prefs.machines.insert(name.clone(), cfg.clone());
                    prefs.active_machine = Some(name);
                    // Clear the legacy pointer so we don't re-migrate next run.
                    prefs.last_config = None;
                    let _ = prefs.save();
                }
            }
        }
        if prefs.active_machine.is_none() {
            new_machine.open();
            opened_new_machine = true;
        }
        let _ = opened_new_machine; // (kept for future telemetry)

        Self {
            fullscreen: false,
            // First-ever launch (no saved size) → fit the window to the monitor
            // on the first frame instead of using the static default verbatim.
            pending_launcher_fit: prefs.window_size.is_none(),
            revealed: false,
            startup_frame: 0,
            prefs,
            cfg,
            cfg_path,
            cfg_dirty: false,
            cfg_dirty_since: None,
            jit: JitEnv::default(),
            tab: Tab::General,
            emu: EmulatorHandle::spawn(),
            toast: None,
            stop_modal: None,
            missing_modal: None,
            confirm_embedded_prom: false,
            new_machine,
            create_disk: CreateDiskDialog::default(),
            show_config_editor: false,
            save_state_name: "snap1".into(),
            restore_state_name: "snap1".into(),
            fb_tex: None,
            last_fb_seq: 0,
            fb_nearest: true,
            fb_scale: 0.0,
            pending_fb_snap: false,
            input_state: input::InputState::default(),
            prev_cpu_halted: true,
            camera_test: None,
            camera_test_tex: None,
            camera_test_seq: 0,
            serial_console: None,
            serial_input: String::new(),
            show_help_info: false,
        }
    }

    fn toast(&mut self, msg: impl Into<String>) {
        self.toast = Some((msg.into(), std::time::Instant::now()));
    }

    /// Mark the in-memory config as edited and arm the auto-save debounce.
    fn mark_dirty(&mut self) {
        self.cfg_dirty = true;
        self.cfg_dirty_since = Some(std::time::Instant::now());
    }

    /// Persist the current machine to disk and clear the dirty flag.
    fn flush_machine(&mut self) {
        if let Some(name) = self.prefs.active_machine.clone() {
            self.prefs.machines.insert(name, self.cfg.clone());
            if let Err(e) = self.prefs.save() {
                self.toast(format!("autosave failed: {e}"));
                return;
            }
        }
        self.cfg_dirty = false;
        self.cfg_dirty_since = None;
    }

    /// Debounced auto-save: flush ~600 ms after the most recent edit.
    fn maybe_autosave(&mut self) {
        if let Some(t) = self.cfg_dirty_since {
            if t.elapsed().as_millis() >= 600 { self.flush_machine(); }
        }
    }

    /// Switch the active machine in-memory and on disk.
    fn switch_to(&mut self, name: &str) {
        // Flush whatever we were holding first.
        if self.cfg_dirty { self.flush_machine(); }
        if let Some(cfg) = self.prefs.machines.get(name).cloned() {
            self.cfg = cfg;
            self.cfg_path = None;
            self.prefs.active_machine = Some(name.to_string());
            let _ = self.prefs.save();
            self.toast(format!("loaded '{name}'"));
        }
    }

    fn save_config(&mut self, path: PathBuf) {
        match cfg_to_toml(&self.cfg) {
            Ok(s) => match std::fs::write(&path, s) {
                Ok(_) => {
                    self.prefs.push_recent(path.clone());
                    self.cfg_path = Some(path);
                    self.cfg_dirty = false;
                    self.toast("config saved");
                }
                Err(e) => self.toast(format!("save failed: {e}")),
            },
            Err(e) => self.toast(format!("serialize failed: {e}")),
        }
    }

    fn start_emulator(&mut self) {
        // Flush any pending edits before the machine starts so the on-disk
        // copy matches what we're about to boot. This also harvests a
        // security-scoped bookmark for any newly user-selected file.
        if self.cfg_dirty { self.flush_machine(); }
        // (Re)assert macOS sandbox access to every bookmarked file *before* the
        // preflight opens them. The startup restore() ran before any bookmark
        // for a freshly-picked file existed, and the file picker's grant does
        // not survive a machine stop/restart — so without re-asserting here the
        // second Start of a session can no longer read the disk image. No-op off
        // the App Store build. See [`macos_sandbox`].
        macos_sandbox::restore(&self.prefs.bookmarks);
        if iris::build_features::LIGHTNING && self.cfg.gdb_port.is_some() {
            // GDB stub is a no-op under lightning; silently drop the setting
            // so we don't hand the executor a port it can't honour.
            self.cfg.gdb_port = None;
        }
        if let Err(e) = self.cfg.validate() {
            self.toast(format!("invalid config: {e}"));
            return;
        }
        // Preflight: Machine::new will call std::process::exit(1) on the
        // first SCSI device whose backing file is missing — we'd lose the
        // GUI process. Catch that case here and prompt the user instead.
        let missing = self.missing_disks();
        if !missing.is_empty() {
            self.missing_modal = Some(MissingDiskModal { missing });
            return;
        }
        // Surface the embedded-PROM fallback so it's clear the start did
        // happen (iris::prom::Prom::from_file_or_embedded handles this
        // transparently — we just echo it to the toast).
        if !std::path::Path::new(&self.cfg.prom).exists() {
            self.toast(format!("'{}' not found — using embedded PROM", self.cfg.prom));
        }
        self.jit.export();
        self.emu.send(Cmd::Start(Box::new(self.cfg.clone())));
        // Snap the window to the emulated display once its first frame arrives
        // (we don't know the guest resolution until then). The on-Start snap
        // supersedes any pending first-launch fit.
        self.pending_fb_snap = true;
        self.pending_launcher_fit = false;
        // Assume halted at boot (idle at the PROM) so the auto-release only
        // fires on a later running→halted transition, not at startup.
        self.prev_cpu_halted = true;
    }

    /// Walk the configured SCSI devices and report any whose image file
    /// is missing. Scratch volumes are skipped (iris auto-creates those).
    /// For CD-ROMs the device is "present" if either the primary path or
    /// any disc in the changer list exists.
    fn missing_disks(&self) -> Vec<MissingDisk> {
        let mut out = Vec::new();
        for (&id, dev) in &self.cfg.scsi {
            if dev.scratch { continue; }
            // Empty CD-ROM (no path, no changer entries) means "drive present,
            // tray empty" — a valid configured state, not missing.
            if dev.cdrom && dev.path.is_empty() && dev.discs.is_empty() {
                continue;
            }
            let primary_ok = disk_readable(&dev.path);
            let any_disc_ok = dev.discs.iter().any(|d| disk_readable(d));
            let present = primary_ok || (dev.cdrom && any_disc_ok);
            if !present {
                out.push(MissingDisk { id, path: dev.path.clone(), cdrom: dev.cdrom });
            }
        }
        out.sort_by_key(|m| m.id);
        out
    }

    /// Detach the given SCSI IDs from the live config and (optionally) try Start again.
    fn detach_and_start(&mut self, ids: &[u8]) {
        for id in ids { self.cfg.scsi.remove(id); }
        self.mark_dirty();
        self.start_emulator();
    }

    fn request_stop(&mut self) {
        let reasons = evaluate(&self.emu.status, &self.cfg);
        if reasons.is_empty() {
            self.emu.send(Cmd::Stop);
        } else {
            self.stop_modal = Some(StopModal { lines: reason_lines(&reasons) });
        }
    }

    fn handle_events(&mut self, ctx: &egui::Context) {
        for evt in self.emu.drain_events() {
            match evt {
                Evt::Started   => self.toast("emulator started"),
                Evt::Stopped   => self.toast("emulator stopped"),
                Evt::PowerOff  => self.toast("guest powered off (safe to stop)"),
                Evt::StateSaved(n)    => self.toast(format!("state saved: {n}")),
                Evt::StateRestored(n) => self.toast(format!("state restored: {n}")),
                Evt::Screenshot(p)    => self.toast(format!("screenshot: {}", p.display())),
                Evt::Error(e)         => self.toast(format!("error: {e}")),
                Evt::Status(_) => {}
            }
        }
        // Repaint cadence: ~60 fps while the emulator is running so we
        // can pull the latest framebuffer; lazy otherwise to save CPU.
        let next = if self.emu.is_running() { 16 } else { 250 };
        ctx.request_repaint_after(std::time::Duration::from_millis(next));
    }

    /// The File/Machine/Memory/SCSI/View/Help menus, stacked vertically for the
    /// left control column. Each is a full-width drop-down button.
    fn menu_list(&mut self, ui: &mut egui::Ui, ctx: &egui::Context) {
        ui.vertical(|ui| {
            ui.menu_button("File  ▶", |ui| {
                ui.set_min_width(220.0);
                if ui.button("New machine…").clicked() {
                    self.new_machine.open();
                    ui.close_menu();
                }
                ui.menu_button("Switch to machine", |ui| {
                    ui.set_min_width(200.0);
                    let active = self.prefs.active_machine.clone();
                    let names: Vec<String> = self.prefs.machines.keys().cloned().collect();
                    if names.is_empty() {
                        ui.label(RichText::new("(no saved machines yet)").weak());
                    }
                    let mut want_switch: Option<String> = None;
                    for name in names {
                        let marker = if active.as_deref() == Some(&name) { "● " } else { "  " };
                        if ui.button(format!("{marker}{name}")).clicked() {
                            want_switch = Some(name);
                            ui.close_menu();
                        }
                    }
                    if let Some(n) = want_switch { self.switch_to(&n); }
                });
                ui.menu_button("Rename current…", |ui| {
                    let cur = self.prefs.active_machine.clone();
                    if let Some(name) = cur {
                        ui.label(format!("Current: {name}"));
                        let mut new_name = name.clone();
                        ui.text_edit_singleline(&mut new_name);
                        if ui.button("Rename").clicked() && !new_name.trim().is_empty() && new_name != name {
                            let n = self.prefs.unique_name(new_name.trim());
                            if let Some(cfg) = self.prefs.machines.remove(&name) {
                                self.prefs.machines.insert(n.clone(), cfg);
                                self.prefs.active_machine = Some(n.clone());
                                let _ = self.prefs.save();
                                self.toast(format!("renamed -> '{n}'"));
                            }
                            ui.close_menu();
                        }
                    } else {
                        ui.label(RichText::new("(no active machine)").weak());
                    }
                });
                let active = self.prefs.active_machine.clone();
                if ui.add_enabled(active.is_some(), egui::Button::new("Delete current machine")).clicked() {
                    if let Some(name) = active {
                        self.prefs.machines.remove(&name);
                        self.prefs.active_machine = self.prefs.machines.keys().next().cloned();
                        if let Some(next) = self.prefs.active_machine.clone() {
                            self.cfg = self.prefs.machines[&next].clone();
                        } else {
                            self.cfg = MachineConfig::default();
                            self.new_machine.open();
                        }
                        let _ = self.prefs.save();
                        self.toast(format!("deleted '{name}'"));
                    }
                    ui.close_menu();
                }
                // iris.toml import/export is a source-build affordance for users
                // who also run the standalone `iris` CLI; the GUI's own gui.json
                // machine store is the system of record. Hidden in pre-compiled /
                // App Store builds (the `bundled` feature). See iris-gui Cargo.toml.
                if !cfg!(feature = "bundled") {
                    ui.separator();
                    if ui.button("Import iris.toml…").clicked() {
                        if let Some(path) = native_open_dialog("Import iris.toml", &[("TOML", &["toml"])]) {
                            let cfg = MachineConfig::load_toml(&path.to_string_lossy());
                            let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("imported");
                            let name = self.prefs.unique_name(stem);
                            self.prefs.machines.insert(name.clone(), cfg.clone());
                            self.prefs.active_machine = Some(name.clone());
                            self.cfg = cfg;
                            self.cfg_path = Some(path);
                            self.flush_machine();
                            self.toast(format!("imported as '{name}'"));
                        }
                        ui.close_menu();
                    }
                    if ui.button("Export current to iris.toml…").clicked() {
                        if let Some(path) = native_save_dialog("Export iris.toml", &[("TOML", &["toml"])]) {
                            self.save_config(path);
                        }
                        ui.close_menu();
                    }
                }
                ui.separator();
                if ui.button("Quit").clicked() {
                    if self.cfg_dirty { self.flush_machine(); }
                    ctx.send_viewport_cmd(ViewportCommand::Close);
                }
            });
            ui.menu_button("Machine  ▶", |ui| {
                let running = self.emu.is_running();
                if ui.add_enabled(!running, egui::Button::new("Start")).clicked() {
                    self.start_emulator();
                    ui.close_menu();
                }
                if ui.add_enabled(running, egui::Button::new("Stop")).clicked() {
                    self.request_stop();
                    ui.close_menu();
                }
                if ui.add_enabled(running, egui::Button::new("Reset")).clicked() {
                    self.emu.send(Cmd::Stop);
                    self.start_emulator();
                    ui.close_menu();
                }
                ui.separator();
                ui.horizontal(|ui| {
                    ui.label("Save state:");
                    ui.add(egui::TextEdit::singleline(&mut self.save_state_name).desired_width(120.0));
                    if ui.button("Save").clicked() {
                        self.emu.send(Cmd::SaveState(self.save_state_name.clone()));
                    }
                });
                ui.horizontal(|ui| {
                    ui.label("Restore state:");
                    ui.add(egui::TextEdit::singleline(&mut self.restore_state_name).desired_width(120.0));
                    if ui.button("Restore").clicked() {
                        self.emu.send(Cmd::RestoreState(self.restore_state_name.clone()));
                    }
                });
                ui.separator();
                if ui.button("Screenshot…").clicked() {
                    if let Some(p) = native_save_dialog("Save screenshot", &[("PNG", &["png"])]) {
                        self.emu.send(Cmd::Screenshot(p));
                    }
                    ui.close_menu();
                }
                if ui.add_enabled(running, egui::Button::new("Serial console…"))
                    .on_hover_text("View the IRIX serial console (ttyd1) over the loopback serial server")
                    .clicked()
                {
                    self.open_serial_console();
                    ui.close_menu();
                }
            });
            ui.menu_button("Memory  ▶", |ui| {
                ui.set_min_width(220.0);
                let total: u32 = self.cfg.banks.iter().sum();
                ui.label(RichText::new(format!("Total: {total} MB")).strong());
                ui.separator();
                ui.label("Quick presets (auto-distributed):");
                for &p in &[32u32, 64, 96, 128, 192, 256] {
                    if ui.button(format!("{p} MB")).clicked() {
                        self.cfg.banks = distribute_ram(p);
                        self.mark_dirty();
                        self.toast(format!("RAM set to {p} MB ({:?})", self.cfg.banks));
                        ui.close_menu();
                    }
                }
                ui.separator();
                ui.label("Per-bank (advanced):");
                for i in 0..4 {
                    ui.menu_button(format!("Bank {i}: {} MB", self.cfg.banks[i]), |ui| {
                        for &sz in iris::config::VALID_BANK_SIZES {
                            if ui.button(format!("{sz} MB")).clicked() {
                                self.cfg.banks[i] = sz;
                                self.mark_dirty();
                                ui.close_menu();
                            }
                        }
                    });
                }
            });
            ui.menu_button("SCSI  ▶", |ui| {
                let action = scsi_menu::draw(ui, &self.cfg);
                match action {
                    scsi_menu::ScsiAction::None => {}
                    scsi_menu::ScsiAction::CreateBlank { id } => {
                        self.create_disk.open_for(id);
                    }
                    other => {
                        if let Some(msg) = scsi_menu::apply(&mut self.cfg, other) {
                            self.mark_dirty();
                            self.toast(msg);
                        }
                    }
                }
            });
            ui.menu_button("View  ▶", |ui| {
                if ui.button(if self.fullscreen { "Exit fullscreen (F11)" } else { "Fullscreen (F11)" }).clicked() {
                    self.fullscreen = !self.fullscreen;
                    ctx.send_viewport_cmd(ViewportCommand::Fullscreen(self.fullscreen));
                    ui.close_menu();
                }
                ui.horizontal(|ui| {
                    ui.label("UI scale");
                    // Adjust the slider freely; only commit to the live zoom
                    // factor on Apply. Applying mid-drag rescales the whole UI
                    // (slider included) under the cursor, which makes the value
                    // jump around — hence the explicit button.
                    ui.add(egui::Slider::new(&mut self.prefs.ui_scale, UI_SCALE_MIN..=UI_SCALE_MAX));
                    if ui.button("Apply").clicked() {
                        ctx.set_zoom_factor(self.prefs.ui_scale);
                        // Re-fit the window so the bigger/smaller controls grow
                        // the window rather than squeezing the picture.
                        self.pending_fb_snap = true;
                    }
                });
                ui.label(RichText::new("Ctrl+= / Ctrl+- / Ctrl+0 to zoom").weak().small());
                ui.separator();
                ui.horizontal(|ui| {
                    ui.label("VM screen");
                    // Sets the emulated-display magnification directly (1× =
                    // native), independent of UI scale. The window resizes to
                    // hold the picture at the chosen size on the next frame.
                    let changed = ui.add(
                        egui::Slider::new(&mut self.prefs.vm_scale, settings::VM_SCALE_MIN..=settings::VM_SCALE_MAX)
                            .step_by(settings::VM_SCALE_STEP)
                            .suffix("×"),
                    ).changed();
                    if changed { self.pending_fb_snap = true; }
                });
                ui.label(RichText::new("1× = native pixels; ¼× steps (½-integers crispest on Retina)").weak().small());
            });
            ui.menu_button("Help  ▶", |ui| {
                ui.label(RichText::new("IRIS — SGI Indy (MIPS R4400) Emulator").strong());
                ui.label(format!("Version {}", env!("APP_VERSION")));
                ui.separator();
                ui.label(RichText::new("Diagnostics").strong());
                let running = self.emu.is_running();
                if ui.add_enabled(running, egui::Button::new("📷 Test Camera…"))
                    .on_hover_text("Preview the host camera used for the emulated IndyCam")
                    .on_disabled_hover_text("Start a machine first")
                    .clicked()
                {
                    self.open_camera_test();
                    ui.close_menu();
                }
                if ui.add_enabled(running, egui::Button::new("🌐 Network test (serial console)…"))
                    .on_hover_text("Connect to the emulator's loopback serial server (127.0.0.1:8881)")
                    .on_disabled_hover_text("Start a machine first")
                    .clicked()
                {
                    self.open_serial_console();
                    ui.close_menu();
                }
                if ui.button("ℹ How camera & networking work…").clicked() {
                    self.show_help_info = true;
                    ui.close_menu();
                }
                ui.separator();
                ui.label(RichText::new("Authors").strong());
                ui.label("Original: techomancer");
                ui.label("iris-gui fork: Dani Sarfati (danifunker)");
                ui.separator();
                ui.horizontal(|ui| {
                    ui.label("Upstream:");
                    ui.hyperlink_to("techomancer/iris", "https://github.com/techomancer/iris");
                });
                ui.horizontal(|ui| {
                    ui.label("This fork:");
                    ui.hyperlink_to("danifunker/iris", "https://github.com/danifunker/iris");
                });
                ui.separator();
                ui.label(RichText::new("Build features:").strong());
                use iris::build_features as bf;
                ui.label(format!("  chd:       {}", if bf::CHD { "on" } else { "off" }));
                ui.label(format!("  camera:    {}", if bf::CAMERA { "on" } else { "off" }));
                ui.label(format!("  jit:       {}", if bf::JIT { "on" } else { "off" }));
                ui.label(format!("  rex-jit:   {}", if bf::REX_JIT { "on" } else { "off" }));
                ui.label(format!("  lightning: {}", if bf::LIGHTNING { "on (no debug)" } else { "off" }));
            });
        });
    }

    /// Start/Stop + save-state controls, stacked full-width for the left column.
    fn machine_controls(&mut self, ui: &mut egui::Ui) {
        let running = self.emu.is_running();
        let full = egui::vec2(ui.available_width(), 0.0);
        if !running {
            if ui.add_sized(full, egui::Button::new(RichText::new("▶ Start").size(16.0))
                .fill(Color32::from_rgb(40, 110, 40))).clicked()
            {
                self.start_emulator();
            }
        } else if ui.add_sized(full, egui::Button::new(RichText::new("■ Stop").size(16.0))
            .fill(Color32::from_rgb(160, 60, 60))).clicked()
        {
            self.request_stop();
        }
        if ui.add_enabled_ui(running, |ui| {
            ui.add_sized(egui::vec2(ui.available_width(), 0.0), egui::Button::new("💾 Save state")).clicked()
        }).inner {
            self.emu.send(Cmd::SaveState(self.save_state_name.clone()));
        }
        if ui.add_enabled_ui(running, |ui| {
            ui.add_sized(egui::vec2(ui.available_width(), 0.0), egui::Button::new("Restore state")).clicked()
        }).inner {
            self.emu.send(Cmd::RestoreState(self.restore_state_name.clone()));
        }
    }

    /// "Edit config" toggle plus the quick-jump tab buttons (shown only while
    /// the config editor is open). Stacked for the left column.
    fn config_quick_buttons(&mut self, ui: &mut egui::Ui) {
        let edit_label = if self.show_config_editor { "Hide config editor" } else { "Edit config…" };
        if ui.add_sized(egui::vec2(ui.available_width(), 0.0), egui::Button::new(edit_label)).clicked() {
            self.show_config_editor = !self.show_config_editor;
        }
        if self.show_config_editor {
            ui.indent("quick_tabs", |ui| {
                if ui.button("Network").clicked()  { self.tab = Tab::Network; }
                if ui.button("Video-In").clicked() { self.tab = Tab::VideoIn; }
                // Debug/JIT is compiled out of lightning builds; CI is hidden
                // in App Store builds — keep the quick-buttons in step with
                // Tab::visible() so they never jump to a hidden tab.
                if !iris::build_features::LIGHTNING && ui.button("Debug").clicked() {
                    self.tab = Tab::Debug;
                }
                if !cfg!(feature = "appstore") && ui.button("CI").clicked() {
                    self.tab = Tab::Ci;
                }
            });
        }
    }

    /// Run-state line (IRIX running / PROM / halted / stopped + MIPS). Used in
    /// the control column's status footer.
    fn run_state_label(&self, ui: &mut egui::Ui) {
        let running = self.emu.is_running();
        let halted = running && self.emu.status.cpu_halted;
        let status = if halted {
            RichText::new("halted — safe to stop").color(Color32::LIGHT_GRAY)
        } else if self.emu.status.in_prom {
            RichText::new("PROM").color(Color32::LIGHT_BLUE)
        } else if running {
            RichText::new("IRIX running").color(Color32::LIGHT_GREEN)
        } else {
            RichText::new("stopped").color(Color32::GRAY)
        };
        ui.label(status);
        if running && !halted {
            ui.label(format!("{:.0} MIPS", self.emu.status.mips));
        }
        if running && self.fb_scale > 0.0 {
            // How magnified the emulated display currently is (1× = native).
            // Round-snap the readout so a whole-number scale reads cleanly.
            let mag = self.fb_scale;
            let whole = (mag - mag.round()).abs() <= 0.01;
            let num = if whole { format!("{:.0}×", mag.round()) } else { format!("{mag:.2}×") };
            let label = if self.fb_nearest {
                RichText::new(format!("{num} scale")).color(Color32::LIGHT_GRAY)
            } else {
                RichText::new(format!("{num} scale · filtered")).color(Color32::from_rgb(200, 175, 90))
            };
            ui.label(label).on_hover_text(
                "On-screen size of the emulated display: logical points per emulated \
                 pixel (1× = native). \"filtered\" means the current size isn't a whole \
                 device-pixel multiple, so the image is smoothed rather than pixel-crisp.",
            );
        }
    }

    /// Resize the window so the central panel exactly holds the emulated
    /// display at native scale — 1 framebuffer pixel = 1 logical point, which
    /// is an integer device-pixel scale on both standard (1×) and HiDPI (2×)
    /// screens, so the picture stays crisp and fills the window without
    /// letterbox bars. Shrinks below native only if that wouldn't fit the
    /// monitor work area. `central_avail` is the framebuffer panel's free space;
    /// `screen_rect − central_avail` is the surrounding chrome (the left control
    /// column, plus the config editor when open) we must keep room for. The math
    /// is orientation-agnostic, so it works whether chrome is a side column or
    /// the older top/bottom bars.
    /// Resizes the window so the display lands at `vm_scale` (clamped to fit the
    /// monitor). Does NOT write the clamped value back to `prefs.vm_scale` — the
    /// slider stays the user's requested scale so it can always be dragged; the
    /// footer readout reports the scale actually achieved.
    fn snap_window_to_fb(ctx: &egui::Context, fb_px: egui::Vec2, central_avail: egui::Vec2, vm_scale: f32) {
        if fb_px.x < 1.0 || fb_px.y < 1.0 { return; }
        // egui-winit reports screen_rect / available_size / monitor_size *and*
        // interprets ViewportCommand::InnerSize all in the same (zoom-scaled)
        // point space, so chrome math stays in egui points.
        let screen = ctx.screen_rect().size();
        let chrome_w = (screen.x - central_avail.x).max(0.0);
        let chrome_h = (screen.y - central_avail.y).max(0.0);
        let zoom = ctx.zoom_factor().max(0.1);
        // Target points-per-pixel for the requested VM scale (vm_scale device
        // pixels per emulated pixel at native backing). Dividing by zoom keeps
        // the picture decoupled from the UI scale, so scaling the controls
        // widens the window instead of shrinking the display.
        let target = (vm_scale / zoom).max(0.01);
        // Always shrink to fit the work area, leaving a clear margin so the
        // window stays obviously windowed (not edge-to-edge). Fall back to a
        // conservative cap if the monitor size isn't reported, so a high VM
        // scale can never blow the window up off-screen and push the controls
        // out of view.
        const MARGIN: f32 = 0.85;
        let (avail_w, avail_h) = match ctx.input(|i| i.viewport().monitor_size) {
            Some(m) => (m.x * MARGIN - chrome_w, m.y * MARGIN - chrome_h),
            None => (1400.0 - chrome_w, 900.0 - chrome_h),
        };
        // Use the requested scale, or the largest that fits when the monitor is
        // the binding constraint. The slider already restricts requests to clean
        // ¼× steps, so we don't snap here — when we must clamp to the monitor we
        // use the full fitting size (the footer readout reports the actual scale
        // and tags non-crisp ones) rather than dropping a whole step.
        let scale = target
            .min((avail_w.max(64.0)) / fb_px.x)
            .min((avail_h.max(64.0)) / fb_px.y)
            .clamp(0.05, target);
        let inner = egui::vec2(fb_px.x * scale + chrome_w, fb_px.y * scale + chrome_h);
        ctx.send_viewport_cmd(ViewportCommand::InnerSize(inner));
    }

    /// Draw the live REX3 framebuffer as an egui image, scaled to fit
    /// the available area while preserving aspect ratio.
    fn framebuffer_panel(&mut self, ui: &mut egui::Ui) {
        // Lock-free check first: only clone + re-upload the (multi-MB)
        // framebuffer when REX3 has actually produced a new frame. Cloning on
        // every 60 fps repaint regardless was ~300 MB/s of pointless copying
        // and needless lock contention with the REX3 refresh thread.
        let seq = self.emu.frame_sink.seq();
        if seq == 0 {
            ui.centered_and_justified(|ui| {
                ui.label(RichText::new("Emulator running — waiting for first REX3 frame…")
                    .color(Color32::LIGHT_GRAY));
            });
            return;
        }

        let avail = ui.available_size();

        // Pick the texture filter from the *device-pixel* scale at which the
        // framebuffer will actually be drawn. At an integer scale (native 1×,
        // 2×, 3×, …) NEAREST keeps every emulated pixel crisp and square. At a
        // fractional scale — which is what most users hit once they set a
        // non-100% UI scale or resize the window freely — NEAREST has to double
        // some source pixels and not others, so e.g. the strokes of a "T" come
        // out uneven; LINEAR (bilinear) spreads the error and looks right. We
        // need the native size to compute this, so on the very first frame
        // (no texture yet) we default to NEAREST and correct on the next frame.
        let zoom = ui.ctx().zoom_factor();
        let want_nearest = match self.fb_tex.as_ref().map(|t| t.size_vec2()) {
            Some(px) if px.x >= 1.0 && px.y >= 1.0 => {
                let size = fb_fit_size(avail, px);
                let scale = size.y * ui.ctx().pixels_per_point() / px.y;
                is_integer_scale(scale)
            }
            _ => true,
        };

        if self.fb_tex.is_none() || seq != self.last_fb_seq || want_nearest != self.fb_nearest {
            let frame = self.emu.frame_sink.snapshot();
            if frame.width == 0 || frame.height == 0 { return; }
            let img = egui::ColorImage::from_rgba_unmultiplied(
                [frame.width, frame.height], &frame.rgba);
            let opts = if want_nearest {
                egui::TextureOptions::NEAREST
            } else {
                egui::TextureOptions::LINEAR
            };
            match &mut self.fb_tex {
                Some(t) => t.set(img, opts),
                None => {
                    self.fb_tex = Some(ui.ctx().load_texture("rex3_fb", img, opts));
                }
            }
            self.last_fb_seq = frame.seq;
            self.fb_nearest = want_nearest;
        }

        // Consume the snap request before the immutable borrow of self.fb_tex.
        let do_snap = std::mem::take(&mut self.pending_fb_snap);

        let mut fb_rect = egui::Rect::NOTHING;
        let mut fb_clicked = false;
        let mut new_fb_scale = 0.0;
        if let Some(tex) = &self.fb_tex {
            let tex_size = tex.size_vec2();
            // First frame after Start (or after a VM/UI scale change): size the
            // window so the picture lands at the requested VM scale.
            if do_snap {
                Self::snap_window_to_fb(ui.ctx(), tex_size, avail, self.prefs.vm_scale);
            }
            // Fill the available area (aspect-preserved). The window — not the
            // image — carries the chosen scale (set by the snap above), so the
            // steady-state draw is stable: no per-frame resize, no jitter.
            let size = fb_fit_size(avail, tex_size);
            // Reported VM scale: device pixels per emulated pixel relative to
            // native backing (1.0 = native). `size` is in zoom-scaled points, so
            // multiply by zoom to recover the zoom-independent figure.
            if tex_size.y >= 1.0 {
                new_fb_scale = size.y * zoom / tex_size.y;
            }
            ui.centered_and_justified(|ui| {
                let response = ui.add(
                    egui::Image::new((tex.id(), size)).fit_to_exact_size(size).sense(egui::Sense::click())
                );
                fb_rect = response.rect;
                // Take keyboard focus so that egui delivers Key events
                // to us instead of routing them to other widgets when
                // the user clicks into the FB.
                if response.clicked() { response.request_focus(); fb_clicked = true; }
            });
        }
        self.fb_scale = new_fb_scale;

        // When the guest becomes "safe to stop" (CPU halted — a clean IRIX
        // shutdown / `halt`), auto-release the captured mouse & keyboard so the
        // user gets their cursor back without pressing Ctrl+Alt+Esc. Edge-
        // triggered on the running→halted transition (prev is reset to true at
        // Start, so idling at the PROM during boot doesn't count), and they can
        // still click the display to re-capture.
        let halted = self.emu.status.cpu_halted;
        if halted && !self.prev_cpu_halted && self.input_state.captured {
            input::force_release(ui.ctx(), &mut self.input_state);
            self.toast("guest halted — mouse released (click display to re-capture)");
        }
        self.prev_cpu_halted = halted;

        // Pump egui input → PS/2 controller. Mouse/keyboard only reach the
        // guest while captured (click the framebuffer to capture, Ctrl+Alt+Esc
        // to release), so menu clicks and config typing don't leak in.
        let ps2 = self.emu.ps2.lock().clone();
        if let Some(ps2) = ps2 {
            input::pump(ui.ctx(), fb_clicked, &ps2, &mut self.input_state, self.cfg.mouse_scroll_pixels_per_line);
        }

        // Capture hint, drawn over the framebuffer.
        if fb_rect.is_positive() {
            let hint = if self.input_state.captured {
                "Ctrl+Alt+Esc to release mouse"
            } else {
                "Click to capture mouse / keyboard"
            };
            ui.painter().text(
                fb_rect.center_bottom() + egui::vec2(0.0, -6.0),
                egui::Align2::CENTER_BOTTOM,
                hint,
                egui::FontId::proportional(12.0),
                Color32::from_white_alpha(140),
            );
        }
    }

    fn central_tabs(&mut self, ui: &mut egui::Ui) {
        ui.horizontal_wrapped(|ui| {
            for t in Tab::visible() {
                ui.selectable_value(&mut self.tab, t, t.label());
            }
        });
        ui.separator();
        match show_tab(ui, self.tab, &mut self.cfg, &mut self.jit) {
            ConfigAction::RequestEmbeddedProm => self.confirm_embedded_prom = true,
            ConfigAction::TestCamera => self.open_camera_test(),
            ConfigAction::None => {}
        }
    }

    /// Open (or restart) the live host-camera preview using the current
    /// `[vino]` standard and camera index. Releases any previous test first.
    fn open_camera_test(&mut self) {
        use iris::video_source::VideoStandard;
        let standard = match self.cfg.vino.standard {
            iris::config::VinoStandard::Ntsc => VideoStandard::Ntsc,
            iris::config::VinoStandard::Pal  => VideoStandard::Pal,
        };
        // Drop the previous instance first so the camera is fully released
        // before re-opening (its Drop joins the capture thread).
        self.camera_test = None;
        self.camera_test_tex = None;
        self.camera_test_seq = 0;
        self.camera_test = Some(camera_test::CameraTest::start(standard, self.cfg.vino.camera_index));
    }

    /// Draw the live host-camera preview window (no-op when closed). Closing it
    /// (or pressing Stop) drops the `CameraTest`, releasing the camera.
    fn camera_test_window(&mut self, ctx: &egui::Context) {
        let Some(test) = &self.camera_test else { return };

        // Pull the latest frame and upload it to the preview texture.
        if let Some((w, h, rgba)) = test.take_new_frame(&mut self.camera_test_seq) {
            let image = egui::ColorImage::from_rgba_unmultiplied([w as usize, h as usize], &rgba);
            match &mut self.camera_test_tex {
                Some(tex) => tex.set(image, egui::TextureOptions::LINEAR),
                None => {
                    self.camera_test_tex =
                        Some(ctx.load_texture("camera-test", image, egui::TextureOptions::LINEAR));
                }
            }
        }
        let status = test.status();
        let error = test.error();

        let mut open = true;
        let mut close_now = false;
        egui::Window::new("Test Camera")
            .open(&mut open)
            .collapsible(false)
            .resizable(false)
            .anchor(egui::Align2::CENTER_CENTER, [0.0, 0.0])
            .show(ctx, |ui| {
                if let Some(e) = &error {
                    ui.colored_label(Color32::from_rgb(200, 80, 80),
                        format!("Camera unavailable: {e}"));
                    ui.label(RichText::new(
                        "Check that a camera is connected and that IRIS has camera \
                         permission (System Settings → Privacy & Security → Camera).")
                        .weak());
                } else if let Some(tex) = &self.camera_test_tex {
                    // The capture field is half-height (interlaced), so present
                    // it at ~4:3 by drawing into a fixed-size rect.
                    ui.add(egui::Image::new(&*tex)
                        .fit_to_exact_size(egui::vec2(480.0, 360.0))
                        .rounding(4.0));
                } else {
                    ui.add_space(110.0);
                    ui.label("Starting capture…");
                    ui.label(RichText::new(
                        "If no image appears, grant camera access in System \
                         Settings → Privacy & Security → Camera, then reopen.")
                        .weak().small());
                }
                ui.add_space(6.0);
                ui.label(RichText::new(&status).weak().small());
                ui.add_space(6.0);
                if ui.button("Close").clicked() {
                    close_now = true;
                }
            });

        if !open || close_now {
            // Drop releases the camera (CameraTest::Drop joins the worker).
            self.camera_test = None;
            self.camera_test_tex = None;
            self.camera_test_seq = 0;
        } else {
            // Keep the preview animating even when egui is otherwise idle.
            ctx.request_repaint_after(std::time::Duration::from_millis(33));
        }
    }

    /// Open (or reconnect) the in-app IRIX serial-console viewer. Connects to
    /// the loopback serial server the running emulator exposes.
    fn open_serial_console(&mut self) {
        self.serial_console = Some(serial_console::SerialConsole::connect());
    }

    /// Draw the in-app serial-console window (no-op when closed). Demonstrates
    /// the loopback serial server: the emulator listens on 127.0.0.1:8881 and
    /// this viewer connects to it.
    fn serial_console_window(&mut self, ctx: &egui::Context) {
        let Some(console) = &self.serial_console else { return };
        let (text, connected, error, _seq) = console.snapshot();

        let mut open = true;
        let mut close_now = false;
        let mut clear_now = false;
        let mut to_send: Option<String> = None;
        egui::Window::new("IRIX Serial Console (ttyd1)")
            .open(&mut open)
            .default_width(620.0)
            .default_height(420.0)
            .resizable(true)
            .show(ctx, |ui| {
                ui.horizontal(|ui| {
                    if let Some(e) = &error {
                        ui.colored_label(Color32::from_rgb(200, 80, 80), e);
                    } else if connected {
                        ui.colored_label(Color32::from_rgb(90, 170, 90),
                            format!("● connected to {}", serial_console::SERIAL_ADDR));
                    } else {
                        ui.label("disconnected");
                    }
                });
                ui.separator();

                egui::ScrollArea::vertical()
                    .stick_to_bottom(true)
                    .auto_shrink([false, false])
                    .max_height(320.0)
                    .show(ui, |ui| {
                        ui.add(
                            egui::Label::new(
                                RichText::new(&text).monospace().size(12.0),
                            )
                            .wrap(),
                        );
                    });

                ui.separator();
                ui.horizontal(|ui| {
                    let resp = ui.add(
                        egui::TextEdit::singleline(&mut self.serial_input)
                            .hint_text("type a command, press Enter")
                            .desired_width(420.0),
                    );
                    let entered = resp.lost_focus() && ui.input(|i| i.key_pressed(egui::Key::Enter));
                    if (ui.button("Send").clicked() || entered) && connected {
                        to_send = Some(std::mem::take(&mut self.serial_input));
                        resp.request_focus();
                    }
                    if ui.button("Clear").clicked() {
                        clear_now = true;
                    }
                    if ui.button("Close").clicked() {
                        close_now = true;
                    }
                });
            });

        if let Some(line) = to_send {
            let mut bytes = line.into_bytes();
            bytes.push(b'\n');
            console.send(&bytes);
        }
        if clear_now {
            console.clear();
        }
        if !open || close_now {
            self.serial_console = None;
        } else if connected {
            // Poll for new console output even when egui is otherwise idle.
            ctx.request_repaint_after(std::time::Duration::from_millis(80));
        }
    }

    /// Explains the camera (IndyCam) and networking features — what they do and
    /// how to use them (for end users), and what host capabilities they use and
    /// why (for App Review). Opened from Help → "How camera & networking work".
    fn help_info_window(&mut self, ctx: &egui::Context) {
        if !self.show_help_info {
            return;
        }
        let mut open = true;
        egui::Window::new("How camera & networking work")
            .open(&mut open)
            .default_width(560.0)
            .default_height(480.0)
            .collapsible(false)
            .resizable(true)
            .show(ctx, |ui| {
                egui::ScrollArea::vertical().max_height(420.0).auto_shrink([false, false]).show(ui, |ui| {
                    ui.heading("📷 Camera — the IndyCam");
                    ui.label(
                        "IRIS emulates the SGI Indy's IndyCam video-input hardware (the VINO device). \
                         When you pick your Mac's camera as the video source, IRIS captures live frames \
                         from it and feeds them to the emulated video input — just as a real IndyCam fed \
                         a real Indy.",
                    );
                    ui.add_space(6.0);
                    ui.label(RichText::new("How to use it").strong());
                    ui.label("• Help → Diagnostics → Test Camera shows a live preview (start a machine first).");
                    ui.label("• Or set Video-In → Source = camera, boot IRIX, and run an IndyCam app like vino/cam.");
                    ui.label("• On first use macOS asks for camera permission. Closing the preview releases the camera.");
                    ui.add_space(6.0);
                    ui.label(RichText::new("Privacy / for App Review").strong());
                    ui.label(
                        "Camera frames are used only as the emulated video input — IRIS never records, \
                         stores, or transmits them. It uses the public AVFoundation API with the \
                         com.apple.security.device.camera entitlement and the NSCameraUsageDescription \
                         purpose string.",
                    );

                    ui.separator();
                    ui.heading("🌐 Networking");
                    ui.label(
                        "The emulated Indy reaches the internet through a built-in user-mode NAT, like a \
                         home router: outbound connections from IRIX are translated onto the host. No \
                         system network settings or elevated privileges are touched.",
                    );
                    ui.add_space(6.0);
                    ui.label(RichText::new("How to use it").strong());
                    ui.label("• The guest serial console (ttyd1) and PROM monitor are exposed on loopback");
                    ui.label("   TCP (127.0.0.1:8881 / 8888) so you can attach a terminal.");
                    ui.label("• Help → Diagnostics → Network test opens an in-app viewer of that console.");
                    ui.label("• Optional inbound port-forwards (Networking tab) let you reach guest services.");
                    ui.add_space(6.0);
                    ui.label(RichText::new("Privacy / for App Review").strong());
                    ui.label(
                        "Outbound guest traffic uses com.apple.security.network.client. The loopback \
                         serial/monitor servers and any inbound port-forwards use \
                         com.apple.security.network.server. Every socket is on loopback or user-initiated; \
                         IRIS opens no network connections on its own.",
                    );
                });
                ui.separator();
                if ui.button("Close").clicked() {
                    self.show_help_info = false;
                }
            });
        if !open {
            self.show_help_info = false;
        }
    }

    fn welcome_panel(&mut self, ui: &mut egui::Ui) {
        ui.add_space(8.0);
        ui.heading("iris — SGI Indy emulator");
        ui.add_space(4.0);

        let name = self.prefs.active_machine.as_deref().unwrap_or("(unsaved)");
        ui.label(format!("Machine: {name}"));
        if self.cfg_dirty {
            ui.label(RichText::new("(autosave pending…)").weak().small());
        }
        ui.add_space(8.0);

        let total_ram: u32 = self.cfg.banks.iter().sum();
        ui.label(RichText::new("Machine summary").strong());
        egui::Grid::new("summary_grid").num_columns(2).striped(true).show(ui, |ui| {
            ui.label("PROM");
            ui.label(if std::path::Path::new(&self.cfg.prom).exists() {
                self.cfg.prom.clone()
            } else {
                format!("{} (missing -> embedded fallback)", self.cfg.prom)
            });
            ui.end_row();
            ui.label("NVRAM");
            ui.label(&self.cfg.nvram);
            ui.end_row();
            ui.label("RAM");
            ui.label(format!("{total_ram} MB ({:?})", self.cfg.banks));
            ui.end_row();
            ui.label("Drives");
            ui.vertical(|ui| {
                let mut ids: Vec<u8> = self.cfg.scsi.keys().copied().collect();
                ids.sort();
                if ids.is_empty() {
                    ui.label(RichText::new("(none)").weak());
                }
                for id in ids {
                    let d = &self.cfg.scsi[&id];
                    let kind = if d.cdrom { "CD" } else { "HDD" };
                    ui.label(format!("scsi{id} {kind}: {}", d.path));
                }
                ui.label(RichText::new("Use the SCSI menu to attach / detach / replace.").weak().small());
            });
            ui.end_row();
            ui.label("Network");
            ui.label(self.cfg.nat_subnet.clone().unwrap_or_else(|| "192.168.0.0/24 (default)".into()));
            ui.end_row();
        });

        ui.add_space(12.0);
        // Welcome panel is only rendered when the emulator is stopped
        // (the central panel switches to the framebuffer when running),
        // so a single Start button is sufficient here.
        if ui.add(egui::Button::new(RichText::new("▶ Start emulator").size(20.0))
            .fill(Color32::from_rgb(40, 120, 40))
            .min_size(egui::vec2(220.0, 44.0))).clicked()
        {
            self.start_emulator();
        }
    }

    /// Status footer for the left control column: run-state, machine name,
    /// dirty-COW count, and the transient toast. Laid out vertically.
    fn status_block(&mut self, ui: &mut egui::Ui) {
        ui.add_space(4.0);
        self.run_state_label(ui);
        ui.separator();
        let name = self.prefs.active_machine.as_deref().unwrap_or("(unsaved)");
        ui.label(format!("Machine: {name}{}", if self.cfg_dirty { " *" } else { "" }));
        ui.label(format!("Dirty COW: {}", self.emu.status.dirty_cow));
        if let Some((msg, when)) = self.toast.clone() {
            if when.elapsed().as_secs() < 5 {
                ui.add_space(2.0);
                ui.label(RichText::new(msg).color(Color32::YELLOW));
            } else {
                self.toast = None;
            }
        }
        ui.add_space(2.0);
    }

    /// The full left control column: machine controls, menus, and config
    /// quick-buttons stacked vertically, with the status block pinned to the
    /// bottom. This replaces the old top menu bar + toolbar + bottom status bar,
    /// freeing vertical space for the (tall, 5:4) emulated display.
    fn control_panel(&mut self, ui: &mut egui::Ui, ctx: &egui::Context) {
        egui::TopBottomPanel::bottom("ctl_status")
            .show_inside(ui, |ui| self.status_block(ui));

        egui::ScrollArea::vertical().show(ui, |ui| {
            ui.add_space(4.0);
            self.machine_controls(ui);
            ui.separator();
            self.menu_list(ui, ctx);
            ui.separator();
            self.config_quick_buttons(ui);
        });
    }
}

impl eframe::App for App {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        self.handle_events(ctx);
        self.maybe_autosave();

        // Remember the current window size so the next launch reopens at it.
        // inner_rect is in logical points — the same unit ViewportBuilder's
        // with_inner_size() takes — so this round-trips regardless of UI zoom.
        // Stored in-memory here; on_exit() (and other save() calls) persist it.
        if let Some(r) = ctx.input(|i| i.viewport().inner_rect) {
            let sz = r.size();
            if sz.x.is_finite() && sz.y.is_finite() && sz.x >= 480.0 && sz.y >= 360.0 {
                self.prefs.window_size = Some([sz.x.round(), sz.y.round()]);
            }
        }

        // F11 toggles fullscreen.
        if ctx.input(|i| i.key_pressed(egui::Key::F11)) {
            self.fullscreen = !self.fullscreen;
            ctx.send_viewport_cmd(ViewportCommand::Fullscreen(self.fullscreen));
        }

        // Ctrl + / Ctrl - / Ctrl 0 zoom controls (helps on Linux where egui's
        // default text size can look small on HiDPI / fractional-scale Wayland).
        let (zoom_in, zoom_out, zoom_reset) = ctx.input(|i| (
            i.modifiers.command && (i.key_pressed(egui::Key::Plus) || i.key_pressed(egui::Key::Equals)),
            i.modifiers.command && i.key_pressed(egui::Key::Minus),
            i.modifiers.command && i.key_pressed(egui::Key::Num0),
        ));
        if zoom_in    { self.prefs.ui_scale = (self.prefs.ui_scale + 0.1).min(UI_SCALE_MAX); ctx.set_zoom_factor(self.prefs.ui_scale); }
        if zoom_out   { self.prefs.ui_scale = (self.prefs.ui_scale - 0.1).max(UI_SCALE_MIN); ctx.set_zoom_factor(self.prefs.ui_scale); }
        if zoom_reset { self.prefs.ui_scale = settings::UI_SCALE_DEFAULT; ctx.set_zoom_factor(self.prefs.ui_scale); }
        // Any UI-zoom change re-fits the window so the controls grow it instead
        // of squeezing the (decoupled) VM screen.
        if zoom_in || zoom_out || zoom_reset { self.pending_fb_snap = true; }

        // The control column lives on the left, always visible (even in
        // fullscreen) — the VM screen sits to its right and never hides it.
        egui::SidePanel::left("control_panel")
            .resizable(false)
            .exact_width(186.0)
            .show(ctx, |ui| self.control_panel(ui, ctx));

        // Config editor lives in a collapsible side panel so the emulator
        // screen (central panel) is never hidden by it. The toolbar's
        // "Edit config… / Hide config editor" toggle drives the collapse;
        // `show_animated` slides it in/out.
        egui::SidePanel::right("config_editor")
            .resizable(true)
            .default_width(420.0)
            .show_animated(ctx, self.show_config_editor, |ui| {
                ui.horizontal(|ui| {
                    ui.heading("Configuration");
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if ui.button("×").on_hover_text("Hide config editor").clicked() {
                            self.show_config_editor = false;
                        }
                    });
                });
                ui.separator();
                egui::ScrollArea::vertical().show(ui, |ui| self.central_tabs(ui));
            });

        // Zero the central panel's inner margin so the emulated display reaches
        // the window edges — every reclaimed pixel makes the (tall, 5:4) picture
        // a little bigger. Keep the dark panel fill so the aspect-ratio
        // letterbox bars stay black.
        let central_frame = egui::Frame::central_panel(&ctx.style())
            .inner_margin(egui::Margin::ZERO);
        egui::CentralPanel::default().frame(central_frame).show(ctx, |ui| {
            // The central panel always shows the emulator screen when the
            // machine is running (the REX3 framebuffer), falling back to the
            // welcome / status summary when idle. The config editor no longer
            // takes this space — it's the side panel above.
            if self.emu.is_running() {
                self.framebuffer_panel(ui);
            } else {
                // First-ever launch: size the window to the monitor for the
                // standard 1280×1024 display before the user sees it (the
                // on-Start snap later re-fits to the actual guest resolution).
                // Wait for the monitor size to be known before consuming the flag.
                if self.pending_launcher_fit
                    && ui.ctx().input(|i| i.viewport().monitor_size).is_some()
                {
                    Self::snap_window_to_fb(ui.ctx(), egui::vec2(1280.0, 1024.0), ui.available_size(), self.prefs.vm_scale);
                    self.pending_launcher_fit = false;
                }
                // Emulator not running: make sure a leftover mouse capture is
                // released so the host cursor isn't stuck hidden/locked.
                input::force_release(ui.ctx(), &mut self.input_state);
                self.welcome_panel(ui);
            }
        });

        // New machine dialog.
        self.new_machine.show(ctx);
        if let Some(result) = self.new_machine.take_result() {
            let name = self.prefs.unique_name(&result.name);
            self.prefs.machines.insert(name.clone(), result.cfg.clone());
            self.prefs.active_machine = Some(name.clone());
            self.cfg = result.cfg;
            self.cfg_path = None;
            self.flush_machine();
            self.toast(format!("created machine '{name}'"));
        }

        // Create blank disk dialog.
        self.create_disk.show(ctx);
        if let Some(result) = self.create_disk.take_result() {
            let path_str = result.path.to_string_lossy().into_owned();
            self.cfg.scsi.insert(result.scsi_id, iris::config::ScsiDeviceConfig {
                path: path_str.clone(), discs: vec![], cdrom: false,
                overlay: false, scratch: false, size_mb: None,
            });
            self.mark_dirty();
            self.toast(format!("created {path_str} and attached at scsi{}", result.scsi_id));
        }

        // Live host-camera test window.
        self.camera_test_window(ctx);

        // In-app IRIX serial-console viewer.
        self.serial_console_window(ctx);

        // Help → "How camera & networking work" explainer.
        self.help_info_window(ctx);

        // Safe-stop confirmation modal.
        let mut close_modal = false;
        let mut do_force = false;
        let mut do_halt  = false;
        if let Some(modal) = &self.stop_modal {
            egui::Window::new("Confirm stop")
                .collapsible(false)
                .resizable(false)
                .anchor(egui::Align2::CENTER_CENTER, [0.0, 0.0])
                .show(ctx, |ui| {
                    ui.label(RichText::new("Stopping now may corrupt the disk image:").strong());
                    for line in &modal.lines { ui.label(format!("• {line}")); }
                    ui.add_space(8.0);
                    ui.horizontal(|ui| {
                        if ui.button("Cancel").clicked() { close_modal = true; }
                        if ui.button("Send IRIX halt").clicked() { do_halt = true; close_modal = true; }
                        if ui.add(egui::Button::new(RichText::new("Force stop").color(Color32::WHITE))
                            .fill(Color32::from_rgb(140, 40, 40))).clicked()
                        {
                            do_force = true; close_modal = true;
                        }
                    });
                });
        }
        if close_modal { self.stop_modal = None; }
        if do_force { self.emu.send(Cmd::Stop); }
        if do_halt  {
            // Type "halt\n" at the IRIX serial console in-process (see
            // EmulatorHandle / Machine::inject_serial_console). This used to
            // open a loopback TCP client to 127.0.0.1:8881; doing it in-process
            // means clean shutdown no longer depends on the serial server
            // socket (which the macOS App Sandbox would otherwise gate behind
            // the network.server entitlement). IRIX takes a few seconds to shut
            // down cleanly; the user can hit Stop once the PROM "halted"
            // message appears.
            self.emu.send(Cmd::HaltIrix);
            self.toast("sent 'halt' to IRIX — wait for shutdown, then Stop");
        }

        // Confirm switching from a custom PROM back to the built-in image.
        if self.confirm_embedded_prom {
            let prom = self.cfg.prom.clone();
            let mut close = false;
            let mut do_clear = false;
            egui::Window::new("Use embedded PROM?")
                .collapsible(false)
                .resizable(false)
                .anchor(egui::Align2::CENTER_CENTER, [0.0, 0.0])
                .show(ctx, |ui| {
                    ui.label(RichText::new("Replace the selected PROM with IRIS's built-in PROM?").strong());
                    ui.label(RichText::new(&prom).weak());
                    ui.add_space(8.0);
                    ui.horizontal(|ui| {
                        if ui.button("Cancel").clicked() { close = true; }
                        if ui.button("Use embedded PROM").clicked() { do_clear = true; close = true; }
                    });
                });
            if do_clear {
                self.cfg.prom.clear();
                self.mark_dirty();
                self.toast("using embedded PROM");
            }
            if close { self.confirm_embedded_prom = false; }
        }

        // Missing-disk modal.
        enum MissingChoice { None, Cancel, Detach, EditDisks }
        let mut choice = MissingChoice::None;
        if let Some(modal) = &self.missing_modal {
            egui::Window::new("Missing disk image(s)")
                .collapsible(false)
                .resizable(false)
                .anchor(egui::Align2::CENTER_CENTER, [0.0, 0.0])
                .show(ctx, |ui| {
                    ui.label(RichText::new("These SCSI image files are missing or can't be read:").strong());
                    for m in &modal.missing {
                        let kind = if m.cdrom { "CD-ROM" } else { "HDD" };
                        ui.label(format!("• scsi{} ({kind}): {}", m.id, m.path));
                    }
                    ui.add_space(8.0);
                    if cfg!(feature = "appstore") {
                        // Under the sandbox an existing file may be unreadable
                        // because the app's access to it lapsed — re-selecting it
                        // re-grants access and stores a bookmark for next launch.
                        ui.label(RichText::new(
                            "If a file exists but still shows here, macOS revoked access \
                             after a previous session. Open the Disks tab and re-select it \
                             to restore access.").weak());
                        ui.add_space(4.0);
                    }
                    ui.label(RichText::new(
                        "iris would terminate the process if started in this state. \
                         Choose how to proceed:").weak());
                    ui.add_space(4.0);
                    ui.horizontal(|ui| {
                        if ui.button("Cancel").clicked() { choice = MissingChoice::Cancel; }
                        if ui.button("Edit Disks tab").clicked() { choice = MissingChoice::EditDisks; }
                        if ui.add(egui::Button::new("Detach missing & start")
                            .fill(Color32::from_rgb(60, 90, 140))).clicked()
                        {
                            choice = MissingChoice::Detach;
                        }
                    });
                });
        }
        match choice {
            MissingChoice::None => {}
            MissingChoice::Cancel => { self.missing_modal = None; }
            MissingChoice::EditDisks => {
                // Switching the tab alone is invisible if the config editor
                // side panel is collapsed (its default state) — open it too,
                // or the button appears to do nothing.
                self.tab = config_ui::Tab::Disks;
                self.show_config_editor = true;
                self.missing_modal = None;
            }
            MissingChoice::Detach => {
                let ids: Vec<u8> = self.missing_modal.as_ref()
                    .map(|m| m.missing.iter().map(|d| d.id).collect())
                    .unwrap_or_default();
                self.missing_modal = None;
                self.detach_and_start(&ids);
            }
        }

        // The window starts hidden so the first frame(s) can fit it to the
        // monitor (the launcher fit, when not running) before it's shown —
        // avoiding a visible open-then-resize. Reveal one frame after the fit
        // settles so its resize has applied, or unconditionally after a short
        // grace period so a missing monitor size can't leave the window hidden.
        if !self.revealed {
            self.startup_frame = self.startup_frame.saturating_add(1);
            let fit_settled = !self.pending_launcher_fit;
            if (fit_settled && self.startup_frame >= 2) || self.startup_frame >= 10 {
                ctx.send_viewport_cmd(ViewportCommand::Visible(true));
                self.revealed = true;
            } else {
                // Keep frames coming while hidden so we reach the reveal.
                ctx.request_repaint();
            }
        }
    }

    fn on_exit(&mut self, _gl: Option<&eframe::glow::Context>) {
        self.prefs.fullscreen = self.fullscreen;
        // Make sure the latest cfg lands in `machines` before save().
        if self.cfg_dirty { self.flush_machine(); } else { let _ = self.prefs.save(); }
        // Synchronously stop the machine and join the worker, so a running
        // guest is cleaned up even if the user closed the window without
        // pressing Stop (rather than relying on Drop ordering / racing
        // process teardown). Bounded by the worker's stop timeout.
        self.emu.shutdown();
        // Release the single-instance lock so the next launch sees a clean
        // start (a crash that skips this just leaves a stale, harmless pidfile).
        single_instance::release();
    }
}

// --- platform dialogs ------------------------------------------------------
//
// We avoid `rfd` as a dependency for now to keep the dep tree slim. Use
// `zenity` / `osascript` if available; otherwise return None and let the
// caller paste a path into the recent-files / save-state fields.
fn native_open_dialog(title: &str, filters: &[(&str, &[&str])]) -> Option<PathBuf> {
    let mut d = rfd::FileDialog::new().set_title(title);
    for (name, exts) in filters { d = d.add_filter(*name, exts); }
    d.pick_file()
}
fn native_save_dialog(title: &str, filters: &[(&str, &[&str])]) -> Option<PathBuf> {
    let mut d = rfd::FileDialog::new().set_title(title);
    for (name, exts) in filters { d = d.add_filter(*name, exts); }
    d.save_file()
}

#[cfg(test)]
mod preflight_tests {
    use super::disk_readable;
    use std::io::Write;

    #[test]
    fn empty_and_missing_paths_are_not_readable() {
        assert!(!disk_readable(""));
        assert!(!disk_readable("/no/such/iris/disk/image.chd"));
    }

    #[test]
    fn an_existing_readable_file_is_readable() {
        let mut p = std::env::temp_dir();
        p.push(format!("iris_readable_{}.raw", std::process::id()));
        std::fs::File::create(&p).unwrap().write_all(b"\0\0\0\0").unwrap();
        assert!(disk_readable(&p.to_string_lossy()));
        let _ = std::fs::remove_file(&p);
    }

    // The case the sandbox actually hits: a file that exists (so Path::exists()
    // is true) but cannot be opened. Simulated with chmod 000. Skipped when the
    // test runs as root, where DAC permission checks are bypassed and the open
    // would still succeed.
    #[cfg(unix)]
    #[test]
    fn an_unreadable_but_present_file_is_not_readable() {
        use std::os::unix::fs::PermissionsExt;
        if unsafe { libc_geteuid() } == 0 {
            return; // root bypasses 000 perms; the distinction can't be shown
        }
        let mut p = std::env::temp_dir();
        p.push(format!("iris_unreadable_{}.raw", std::process::id()));
        std::fs::File::create(&p).unwrap().write_all(b"\0\0\0\0").unwrap();
        std::fs::set_permissions(&p, std::fs::Permissions::from_mode(0o000)).unwrap();
        // exists() says present, but disk_readable() must say no.
        assert!(p.exists());
        assert!(!disk_readable(&p.to_string_lossy()));
        let _ = std::fs::set_permissions(&p, std::fs::Permissions::from_mode(0o600));
        let _ = std::fs::remove_file(&p);
    }

    #[cfg(unix)]
    extern "C" {
        #[link_name = "geteuid"]
        fn libc_geteuid() -> u32;
    }
}
